language: node_js
node_js:
  - node
cache:
  directories:
    - 'node_modules'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci # installs from package lock
script:
  - npm run build-deploy
  - rm -rf node_modules # delete node_modules before deploying, since we skip cleanup
deploy:
  skip_cleanup: true
  provider: heroku
  app: snekio
  api_key:
    secure: 'EJ9fbJzG7l8YyvoHNUPQEtjJgTcEjCmsuT/Jd+8olQO9r5JsHJQ1wkXNe0srZLrOVVeym1SONRhR9e6ZORdsi9HhwExEa3tv1rppuGJNq8ztuwjWPQg4rufEs9nc3sjHzYdKnQx0ARAZP8Yng6KPMjLWf9336f9dtBWwL+qLQMWY5+B56djHG3jLTwakEJNwD9dU1/EuDTgBhJ5xK8syvKpkuYxCt/AWIxF/RtsaJgJQvXPyc3jSRoS8h6yMOw9OcwChx9oiTS/bESgfu/EbuKvQx5e3uRGLptP8/Zk+mtaZfuhiyle3YbYOc6TKChdiJbUxXu0y2hANB86qaLTm3csWqSofl+fBFyol/FGkzM9rvXBf+N9YeLkPshWkToFBax+HohhaArZQAv11AYUNiLJUzaxjJ24gn/je6jLTvjrjrtZEqYc5gMbXlOwHbx1gBkF48Vy9FN+5BiAgfCqZlhdtIBEFOvT5QoylEGIAiNdr+OBKyFKQDdB+k5mYmqSp3H35s41kd+jeD4qktn2SDDrf5Z9kVXhfuFAxXa4jE7ZQQlTgjailN6FKNJOBQB54FP2MNy49Y8ELcKUMaOs6jH+E/qZx4yKtScu0FKl06HHjktIAUUQhEGt2MwwcpHYeGobAxCtWyyck4ZK3whMFOoM5mNT37zMxArosWNctSlQ='
